# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 14, 10, 18, 162601, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 14, 10, 18, 161750, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='read_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 14, 10, 18, 161798, tzinfo=utc), verbose_name='date read'),
        ),
    ]
