# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:22
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20170428_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
