# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20170428_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='intro',
            field=models.CharField(default='test intro', max_length=500),
            preserve_default=False,
        ),
    ]
