# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20170429_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
    ]
