# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 07:21
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20170502_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='text',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
